# PGADMIN_DEFAULT_EMAIL=admin@example.com
# PGADMIN_DEFAULT_PASSWORD=changeme
# FQDN_PGADMIN=pgadmin.example.com
# OAUTH_CLIENT_ID=pgadmin
# OAUTH_CLIENT_SECRET=insecure_secret
# AUTHENTIK_URL=https://auth.prod.dlplab.app
# TZ=Australia/Sydney
---
volumes:
  pgadmin_storage:

networks:
  frontend:
    external: true

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    container_name: pgadmin
    networks: ['frontend']
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.pgadmin-https.tls=true"
      - "traefik.http.routers.pgadmin-https.tls.certresolver=route53"
      - "traefik.http.routers.pgadmin-https.rule=Host(`${FQDN_PGADMIN}`)"
      - "traefik.http.routers.pgadmin-https.entrypoints=websecure"
      - "traefik.http.routers.pgadmin-https.service=pgadmin-svc"
      - "traefik.http.services.pgadmin-svc.loadbalancer.server.port=80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - CA_CERTS=/certs/dlplab-root-v5.pem
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - AUTHENTIK_URL=${AUTHENTIK_URL}
      - TZ=${TZ}
    volumes:
      - pgadmin_storage:/var/lib/pgadmin
      - /docker/compose/pgadmin/certs/dlplab-root-v5.pem:/certs/dlplab-root-v5.pem:ro
      - /docker/compose/pgadmin/config_local.py:/pgadmin4/config_local.py:ro
